class BattleConstants:
    # https://www.carlsguides.com/strategy/civilization5/war/combatbonuses.php
    LANDING_MALUS = -50
    BOARDING_MALUS = -50
    ATTACKING_ACROSS_RIVER_MALUS = -20
    BASE_FLANKING_BONUS = 10.0
    MISSING_RESOURCES_MALUS = -25
    EMBARKED_DEFENCE_BONUS = 100
    FORTIFICATION_BONUS = 20
    DAMAGE_REDUCTION_WOUNDED_UNIT_RATIO_PERCENTAGE = 300.0
    DAMAGE_TO_CIVILIAN_UNIT = 40