[workspace]
members = [ "ai", "automation", "barbarians", "battle", "city", "civilization", "core", "diplomacy", "espionage", "main", "map", "mods", "multiplayer", "rules", "simulation", "trade", "ui", "units", "util"]
