#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DiplomaticModifiers {
    // Negative
    DeclaredWarOnUs,
    WarMongerer,
    CapturedOurCities,
    DeclaredFriendshipWithOurEnemies,
    BetrayedDeclarationOfFriendship,
    SignedDefensivePactWithOurEnemies,
    BetrayedDefensivePact,
    Denunciation,
    DenouncedOurAllies,
    RefusedToNotSettleCitiesNearUs,
    RefusedToNotSpreadReligionToUs,
    BetrayedPromiseToNotSettleCitiesNearUs,
    BetrayedPromiseToNotSpreadReligionToUs,
    UnacceptableDemands,
    UsedNuclearWeapons,
    StealingTerritory,
    DestroyedProtectedMinor,
    AttackedProtectedMinor,
    AttackedAlliedMinor,
    BulliedProtectedMinor,
    SidedWithProtectedMinor,
    SpiedOnUs,
    StoleOurAlly,

    // Positive
    YearsOfPeace,
    SharedEnemy,
    LiberatedCity,
    DeclarationOfFriendship,
    DeclaredFriendshipWithOurAllies,
    DefensivePact,
    SignedDefensivePactWithOurAllies,
    DenouncedOurEnemies,
    OpenBorders,
    FulfilledPromiseToNotSettleCitiesNearUs,
    FulfilledPromiseToNotSpreadReligion,
    GaveUsUnits,
    GaveUsGifts,
    ReturnedCapturedUnits,
    BelieveSameReligion,
}

impl DiplomaticModifiers {
    pub fn text(&self) -> &'static str {
        match self {
            // Negative
            Self::DeclaredWarOnUs => "You declared war on us!",
            Self::WarMongerer => "Your warmongering ways are unacceptable to us.",
            Self::CapturedOurCities => "You have captured our cities!",
            Self::DeclaredFriendshipWithOurEnemies => "You have declared friendship with our enemies!",
            Self::BetrayedDeclarationOfFriendship => "Your so-called 'friendship' is worth nothing.",
            Self::SignedDefensivePactWithOurEnemies => "You have declared a defensive pact with our enemies!",
            Self::BetrayedDefensivePact => "Your so-called 'defensive pact' is worth nothing.",
            Self::Denunciation => "You have publicly denounced us!",
            Self::DenouncedOurAllies => "You have denounced our allies",
            Self::RefusedToNotSettleCitiesNearUs => "You refused to stop settling cities near us",
            Self::RefusedToNotSpreadReligionToUs => "You refused to stop spreading religion to us",
            Self::BetrayedPromiseToNotSettleCitiesNearUs => "You betrayed your promise to not settle cities near us",
            Self::BetrayedPromiseToNotSpreadReligionToUs => "You betrayed your promise to not spread your religion to us",
            Self::UnacceptableDemands => "Your arrogant demands are in bad taste",
            Self::UsedNuclearWeapons => "Your use of nuclear weapons is disgusting!",
            Self::StealingTerritory => "You have stolen our lands!",
            Self::DestroyedProtectedMinor => "You destroyed City-States that were under our protection!",
            Self::AttackedProtectedMinor => "You attacked City-States that were under our protection!",
            Self::AttackedAlliedMinor => "You attacked our allied City-States!",
            Self::BulliedProtectedMinor => "You demanded tribute from City-States that were under our protection!",
            Self::SidedWithProtectedMinor => "You sided with a City-State over us",
            Self::SpiedOnUs => "You spied on us!",
            Self::StoleOurAlly => "You took the alliance we had with a City-State",

            // Positive
            Self::YearsOfPeace => "Years of peace have strengthened our relations.",
            Self::SharedEnemy => "Our mutual military struggle brings us closer together.",
            Self::LiberatedCity => "We applaud your liberation of conquered cities!",
            Self::DeclarationOfFriendship => "We have signed a public declaration of friendship",
            Self::DeclaredFriendshipWithOurAllies => "You have declared friendship with our allies",
            Self::DefensivePact => "We have signed a promise to protect each other.",
            Self::SignedDefensivePactWithOurAllies => "You have declared a defensive pact with our allies",
            Self::DenouncedOurEnemies => "You have denounced our enemies",
            Self::OpenBorders => "Our open borders have brought us closer together.",
            Self::FulfilledPromiseToNotSettleCitiesNearUs => "You fulfilled your promise to stop settling cities near us!",
            Self::FulfilledPromiseToNotSpreadReligion => "You fulfilled your promise to stop spreading religion to us!",
            Self::GaveUsUnits => "You gave us units!",
            Self::GaveUsGifts => "We appreciate your gifts",
            Self::ReturnedCapturedUnits => "You returned captured units to us",
            Self::BelieveSameReligion => "We believe in the same religion",
        }
    }
}