[package]
name = "units"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
serde = { version = "1.0.219", features = ["derive"] }
map = { path = "../map" }
rules = { path = "../rules" }
util = { path = "../util" }
